image: docker:latest
services:
  - name: docker:dind
    command: ["dockerd-entrypoint.sh", "--insecure-registry=192.168.200.154:8131"]
  
stages:
  - build
  - deploy

variables:
  REPO_NEXUS: "192.168.200.154:8131/repository"
  IMAGE_NAME: ${REPO_NEXUS}/simple-webapp
  
build:
  stage: build
  only:
    - tags
  tags:
    - docker
  before_script:
    - docker login ${REPO_NEXUS} -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
  script:
    - docker build -t ${IMAGE_NAME}:${CI_COMMIT_TAG} .
    - docker push ${IMAGE_NAME}:${CI_COMMIT_TAG}
    - docker rmi ${IMAGE_NAME}:${CI_COMMIT_TAG}

deploy:
  stage: deploy
  image: dtzar/helm-kubectl:3.9
  only:
    - tags
  tags:
    - docker
  script:
    - kubectl config set-cluster k8s --server="${SERVER}"
    - kubectl config set clusters.k8s.certificate-authority-data ${CERTIFICATE_AUTHORITY_DATA}
    - kubectl config set-credentials gitlab --token="${USER_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab
    - kubectl config use-context default
    - helm upgrade simple-webapp ./simple-webapp --install --set deployment.image.tag=${CI_COMMIT_TAG}
