---

apiVersion: v1

kind: ServiceAccount
metadata:
  name: gitlab-service-account
---

apiVersion: rbac.authorization.k8s.io/v1

kind: ClusterRoleBinding
metadata:
  name: gitlab-service-account-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: gitlab-service-account
    namespace: default
    
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secret
  annotations:
    kubernetes.io/service-account.name: gitlab-service-account
type: kubernetes.io/service-account-token
