apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.deployment.app }}
  name: service-{{ .Chart.Name }}
spec:
  ports:
  - port: {{ .Values.service.ports.port }}
    targetPort: {{ .Values.service.ports.targetPort }}
    nodePort: {{.Values.service.ports.nodePort}}
  selector:
    app: {{ .Values.deployment.app }}
  type: {{ .Values.service.type }}
